# Generated by Django 4.2.5 on 2023-09-27 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pirogues', '0003_position_is_visible_position_securite_and_more'),
        ('alertes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerte',
            name='last_pirogue_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pirogues.position'),
        ),
    ]
