# Generated by Django 4.2.5 on 2023-09-27 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertes', '0003_alerte_last_pirogue_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alerte',
            name='last_pirogue_position',
        ),
        migrations.AddField(
            model_name='alerte',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alerte',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
