# Generated by Django 4.2.5 on 2023-09-29 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertes', '0004_remove_alerte_last_pirogue_position_alerte_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerte',
            name='type_alerte',
            field=models.CharField(choices=[('mayday', 'Mayday'), ('informations', 'Informations')], default='mayday', max_length=20),
        ),
    ]
