# Generated by Django 4.2.5 on 2023-09-16 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pirogues', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pirogue',
            name='is_marine',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pirogue',
            name='tel',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
