# Generated by Django 4.2.5 on 2023-09-21 09:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pirogues', '0002_alter_pirogue_is_marine_alter_pirogue_tel'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='position',
            name='securite',
            field=models.CharField(choices=[('vert', 'Vert'), ('orange', 'Orange'), ('rouge', 'Rouge')], default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='position',
            name='temps_transmission',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='vitesse',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
